# Generated by Django 5.2.5 on 2025-08-13 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_alter_carditem_card'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
